#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable

-define(SIZE, 12).

timestable(N, SendPid) ->
    compute_times(N, ?SIZE, SendPid).

compute_times(_X, 0, _Pid) ->
    ok;
compute_times(X, I, Pid) ->
    Pid ! {result, X, I, X*I, self()},
    compute_times(X, I-1, Pid).

main([UpperBound]) ->
    try
        N = list_to_integer(UpperBound),
    	spawn_workers(N, self()),
        listen(0, N*?SIZE)
    catch
        _:_ -> usage()
    end.

listen(R, R) ->
    ok;
listen(R, Max) ->
    NewR = receive
        {result, X, I, Quot, From} -> 
            io:format("~w x ~w = ~w (~w)~n", [X, I, Quot, From]),
            R + 1
    end,
    listen(NewR, Max).

usage() ->
    io:format("usage: timestable2 integer\n"),
    halt(1).

spawn_workers(0, _SendPid) ->
    ok;
spawn_workers(N, SendPid) ->
    spawn(fun() -> timestable(N, SendPid) end),
    spawn_workers(N-1, SendPid).
